---
- import_playbook: task-02-features.yml

- hosts: spines, leafs
  gather_facts: false

  roles:
    - role: common
    - role: underlay

- import_playbook: task-03-vlans.yml

- import_playbook: task-04-vrfs.yml

- import_playbook: task-05-nve.yml