---
- name: Task 09 - Deploy networks
  hosts: ndfc1
  gather_facts: false

  vars_files:
    - vars.yml

  vars:
    ndfc: &ndfc
      fabric: "{{ fabric }}"
      state: merged

  tasks:
    - name: Add networks and attach to interfaces
      cisco.dcnm.dcnm_network:
        <<: *ndfc
        config:
          - net_name: "{{ item.name }}"
            vrf_name: "{{ item.vrf }}"
            net_id: "{{ item.id }}"
            vlan_id: "{{ item.vlan }}"
            gw_ip_subnet: "{{ item.gateway }}"
            attach:
              - ip_address: "CHANGE ME"
                ports: "CHANGE ME"
            deploy: true
      loop: "{{ networks }}"