---
- name: Task 08 - Deploy VRF
  hosts: ndfc1
  gather_facts: false

  tasks:
    - name: Add VRF
      cisco.dcnm.dcnm_vrf:
        config:
          - vrf_name: "CHANGE ME"
            vrf_id: "CHANGE ME"
            vlan_id: "CHANGE ME"
            deploy: true