---
- name: Task 10 - Change interface to access mode
  hosts: ndfc1
  gather_facts: false

  vars_files:
    - vars.yml

  tasks:
  - name: Change interface to access mode
    cisco.dcnm.dcnm_interface:
      fabric: "{{ fabric }}"
      config:
        - name: "{{ interfaces[0].name }}"
          switch:
            - "{{ interfaces[0].switch }}"
          profile:
            access_vlan: "{{ interfaces[0].vlan }}"
            mode: access
          type: eth
          deploy: true
        - name: "CHANGE ME"
          switch:
            - "CHANGE ME"
          profile:
            mode: access
            access_vlan: "CHANGE ME"
          type: eth
      state: merged