---
# spines.yml

features: 
  - CHANGE ME

bgp_asn: 65001

bgp_neighbors:
  - neighbor: 10.0.0.101
    remote_as: 65001
    update_source: Loopback0
  - neighbor: 10.0.0.102
    remote_as: 65001
    update_source: Loopback0
  - neighbor: 10.0.0.103
    remote_as: 65001
    update_source: Loopback0
